// COMPARACIONES
// OPERADOR    DESCRIPCIÓN
// ==          Igual a ... 
// !=          Diferente a ... 
// >           Mayor a ... 
// <           Menor a ... 
// >=          Mayor o igual ...
// <=          Manor o igual ... 
// ===         Igual a ... y mismo tipo de dato ...

// Toda comparación en programación, devuelve un valor Booleano (true/false)
console.log(5 == 5);  // true
console.log(5 == 6);  // false
console.log(5 != 6);  // true
console.log(5 > 6);  // false
console.log(5 >= 5);  // true
console.log("5" == 5);  // true
console.log("5" === 5);  // false